apiVersion: apps/v1
kind: Deployment
metadata:
  name: school-deployment
  namespace: spring-cloud
  labels:
    app: school
spec:
  replicas: 1
  selector:
    matchLabels:
      app: school
  template:
    metadata:
      labels:
        app: school
    spec:
      containers:
      - name: school
        image: localhost:32000/datacenter-school:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ADDRESS
          value: mysql:3306
        - name: MYSQL_PASSWORD
          value: bocloud@2019
        ports:
        - containerPort: 8084

