apiVersion: apps/v1
kind: Deployment
metadata:
  name: teacher-deployment
  namespace: spring-cloud
  labels:
    app: teacher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teacher
  template:
    metadata:
      labels:
        app: teacher
    spec:
      containers:
      - name: teacher
        image: datacenter-teacher:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ADDRESS
          value: mysql:3306
        - name: MYSQL_PASSWORD
          value: bocloud@2019
        ports:
        - containerPort: 8082

